version: '3.8'
services:
  app:
    build:
      context: ./server
      target: dev
    ports:
      - '7000:7000'
    restart: always
    tty: true
    depends_on:
      - db
    volumes:
      - ./server:/opt/app/server:delegated
  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
