name: Deploy Frontend
on: 
  push:
    branches:
      - "master"
    paths:
      - "**.tsx"
      - "**.ts"
      - "**.css"

jobs:
  build:
    name: Build React
    runs-on: ubuntu-latest
    timeout-minutes: 300
    container:
      image: node:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: npm install
        working-directory: ./web
      - name: Build
        run: npm run build
        working-directory: ./web
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: frontend-build-artifact
            path: ./web/build
  deploy:
    name: Deploy React
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
            name: frontend-build-artifact
            path: ./web/build
      - name: Deploy to S3
        env:
          FRONTEND_BUCKET: ${{ secrets.FRONTEND_BUCKET_NAME }}
        run: |
          aws s3 cp ./web/build s3://stg-frontend-origin